pipeline {
    agent any
    stages {
        stage('Build Backend Image') {
            steps {
                sh 'docker build -t backend-app CC_LAB-6/backend'
            }
        }
        stage('Deploy Backends') {
            steps {
                sh '''
                # Remove containers if they exist
                docker rm -f backend1-new backend2-new || true
                
                # Run with Network Attached
                docker run -d --name backend1-new --network lab6-net backend-app
                docker run -d --name backend2-new --network lab6-net backend-app
                '''
            }
        }
        stage('Deploy NGINX') {
            steps {
                sh '''
                # Remove LB if it exists
                docker rm -f nginx-lb-new || true

                # 1. Start Nginx on the SAME network
                docker run -d --name nginx-lb-new --network lab6-net -p 80:80 nginx

                # 2. Copy the config file
                docker cp CC_LAB-6/nginx/default.conf nginx-lb-new:/etc/nginx/conf.d/default.conf

                # 3. Reload Nginx
                docker exec nginx-lb-new nginx -s reload
                '''
            }
        }
    }
}
