pipeline {
    agent any
    stages {
        stage('Build Backend Image') {
            steps {
                sh 'docker build -t backend-app CC_LAB-6/backend'
            }
        }
        stage('Deploy Backends') {
            steps {
                sh '''
                docker rm -f backend1 backend2 || true
                docker run -d --name backend1 backend-app
                docker run -d --name backend2 backend-app
                '''
            }
        }
        stage('Deploy NGINX') {
            steps {
                sh '''
                # Remove old container if it exists
                docker rm -f nginx-lb || true

                # 1. Start Nginx WITHOUT the volume mount first
                docker run -d --name nginx-lb -p 80:80 nginx

                # 2. Copy the config file from Jenkins workspace to the Container
                # (We use the full path seen in your logs to be safe)
                docker cp CC_LAB-6/nginx/etc/nginx/conf.d/default.conf nginx-lb:/etc/nginx/conf.d/default.conf

                # 3. Reload Nginx so it uses the new config
                docker exec nginx-lb nginx -s reload
                '''
            }
        }
    }
}
